Kozea/CairoSVG

cairosvg/__init__.py
When using CairoSVG as part of a frozen app (esky, py2exe, py2app, etc...) that uses the highest optimization level (python -OO), CairoSVG fails to import.
=> Allow Surface.convert.__doc__ to be None when running under -OO 

documentation.md
And specify that the parameters must be named, which is what confused me in https://github.com/Kozea/CairoSVG/issues/10#issuecomment-200862896
=> Add usage examples

cairosvg/bounding_box.py
Small bug in getting the bounding box for a polyline. Does not show with current testset (no gradient patterns in there).
Attached is an example file to demonstrate bug.
[fix_bbox_polyline.zip](https://github.com/Kozea/CairoSVG/files/250198/fix_bbox_polyline.zip)
=> Fixed bbox for polyline

.gitignore, cairosvg/__init__.py, cairosvg/parser.py
This change allows svg2png to parse "large" SVG files. I believe that this limit varies system-by-system, but it was causing problems for me on Ubuntu with files larger than 9.5mb. Before this change, parsing a large file resulted in:
```
lxml.etree.XMLSyntaxError: internal error: Huge input lookup
```
=> Allow large SVG files

cairosvg/path.py
This fix makes CairoSVG a bit more compliant with the SVG specs.
The test https://github.com/Kozea/CairoSVG/blob/master/test/fail/draft/types-basic-02-f.svg now fails a bit less ;-). After this patch and the patch for case sensitivity in style declarations (other pull request), only 1 issue remains for this test: within presentation attributes lengths should be lowercase (eg the following is incorrect: \<circle stroke-width="10PX" ...\>).
Cheers,
Erik
=> Small fix in parsing arc in path (only allow 0 or 1 for flags)

.gitignore, cairosvg/helpers.py, cairosvg/image.py, cairosvg/path.py, cairosvg/svg.py
Fixed that markers are scaled and clipped properly.
Reused some of the existing code for preserving aspect ratio, but had to tweak it as well. (Same as in the fix for gradient patterns, let me know if you feel this requires refactoring.)
Two existing tests will fail (but actually work ;-):
- marker.svg - actually it was not scaled correct in the original (fixed now)
- painting-marker-03-f.svg - difficult to see what actually changed (seems okay)
Two additional tests are now okay:
- fail/marker/painting-marker-02-f.svg (property inheritance)
- fail/marker/painting-marker-05-f.svg (visibility, ie clipping)
There are still some issues with two other 'marker' tests. These are the result of the way attributes and properties are handled. Changing/fixing this will require a bit more work, but it …
=> Fixed scaling and clipping of markers

.gitignore, cairosvg/bounding_box.py, cairosvg/defs.py, cairosvg/helpers.py, cairosvg/parser.py
Guillaume,
I have added a fix for the case sensitivity of style declarations.
In short, all declarations are still made lowercase (making them case insensitive), **except for**:
- id's
- classes
- font-names (defined through font and through font-family)
- url's (optional part of many declarations like stroke/paint/filter/mask/marker-start/...)
All style names are made lowercase.
Cheers,
Erik
=> Case sensitivity for style declarations

cairosvg/__init__.py, cairosvg/surface.py
As seen in #83.
Adds the `-s | --scale [N]` parameter to scale output dimensions by `N`.
=> Add --scale parameter

cairosvg/bounding_box.py, cairosvg/css.py, cairosvg/defs.py, cairosvg/image.py, cairosvg/parser.py, cairosvg/url.py
Added URLFetcher class to handle the retrieval of URLs (CSS, images, etc). The class is setup in such a way that it allows new child-fetchers to be created. This can be used for example to handle images in a special way. The class also allows restricting the URLs retrieved. This can be used to prevent URLs like "file:///dev/passwd" from being used. A feature useful if CairoSVG is part of a server application.
Currently there is only a default URLFetcher implementation which allows all URLs. This is similar to the current implementation.
=> Add URLFetcher

cairosvg/text.py
There were code paths accessible resulting in a traceback triggered by Y_align being undefined. I didn't investigate further why this happened, the problem was triggered by SVG generated by fabric.js. Since having code paths with undefined variables in them is not only ugly but an error I suggest to correct the error in the way suggested by the pull request because this a coverage only change to the code.
=> Moved the two variables x/y_align to the top of the function

cairosvg/__init__.py, cairosvg/surface.py
I added output_width and output_height parameters to the converter. This is helpful when you want to resize an svg without knowing the original size.
The scale is computed from one parameter if only one dimension is specified, otherwise the width and height fields of the surface are directly set to the desired output size.
=> Add output size parameters

cairosvg/__main__.py, cairosvg/surface.py, cairosvg/text.py
Decreases PDF file size and allows text selection/copy by rendering the texts as text, instead of paths.
Fixes issue #212.
=> Fix for PDF texts not being selectable

cairosvg/parser.py
This solves an issue that might happen when a resource doesn't have a physical location but is loaded from memory and includes reference to itself via the `use` element:
```xml
<use xlink:href="#reference"/>
```
If the SVG is loaded from a physical location then there is no problem except the resource will be loaded and processed again.
=> If the referenced url starts with '#' and no URL is given, use root parent's tree

cairosvg/__init__.py, cairosvg/__main__.py, cairosvg/colors.py, cairosvg/defs.py, cairosvg/image.py, cairosvg/surface.py
This PR adds `--background_color` (`-bg`), `--negate_colors` (`-n`), and `--invert-images` (`-i`) options to CairoSVG.
**Sample output** (not included in this PR):  
https://github.com/mingaldrichgan/CairoSVG/tree/negate-out/test_non_regression/out
=> Add background_color, negate_colors, and invert_images options

pages/svg_support.rst, pages/user_documentation.rst
Your link for the "Pillow" package is incorrect. It should be [https://python-pillow.org/](https://python-pillow.org/).
I posted issue #256.
=> Fixed incorrect link to Pillow package website

cairosvg/text.py
Cairo only exposes "NORMAL" and "BOLD" weights; this patch interprets
numeric weights >= 550 as bold (previously any numeric weight was
interpreted as NORMAL).
The CSS standard says
- 400 = Normal, 500 = Medium, 600 = Semi Bold, 700 = Bold
and also says that applying "bolder" (resp. "lighter") to fonts with
- 350 <= w < 550 -> gives 700 (resp. 100)
- 550 <= w < 750 -> gives 900 (resp. 400)
hence the choice of a cutoff at 550.
I would need some help as to how to add a test, if required (but I tested the patch locally).
=> Improve support for font weights.

cairosvg/__init__.py
Solves the same issue as documented in my other pull request. See that page for more details: https://github.com/Kozea/WeasyPrint/pull/1089
=> Try fixing a bug encountered when using cairosvg in Pyinstaller context

cairosvg/image.py
This should fix #278 Pillow had a [method](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.exif_transpose) to make the transformations according to EXIF orientations already, I just imported and applied in place.
I am not sure if I should have run any kind of tests, please let me know if I need to update and/or provide tests and documentation based on this fix
=> Adds Exif Transposition Support

cairosvg/text.py, test_non_regression/svg/dominant_alignment_baseline.svg
"alignment-baseline" works as "dominant-baseline" but is only valid on
text elements: `<tspan>`, `<tref>`, `<altGlyph>`, and `<textPath>`.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
I also added a sample SVG file for  regression testing.
File generated by Cairo
Svg rendered in browser:
=> use "dominant-baseline" in addition to "alignment-baseline"

README.rst, cairosvg/__init__.py, cairosvg/surface.py, setup.py
Added the ability to convert to encapsulated postscript (EPS) in addition to ordinary postscript, as described in Issue #294. The main difference is a new `svg2eps` function and an `EPSSurface` class which, following the pattern of `PNGSurface`, overrides the default `_create_surface()` method. In order to create an EPS surface, we simply create an ordinary `PSSurface`, and then call `set_eps(True)` as documented here: https://cairocffi.readthedocs.io/en/latest/api.html?highlight=set_eps#cairocffi.PSSurface.set_eps
=> Added option to convert to EPS (encapsulated postscript)

cairosvg/helpers.py
If root tag is unexpected in svg (say, 'html', which can occasionally be
encountered), the error is previously somewhat cryptic; this commit
offers an explicit message.
=> Adding error message for unexpected root tag.

cairosvg/path.py
TLDR: coordinates and angles in the array used to render markers get out of sync after an unclosed sub-path.
In path.py, `node.vertices` keeps track of the vertices of the path being parsed, and consists of alternating pairs of (x,y) coordinates and outgoing and incoming angles. The list is used by the draw_markers() function in the same file, which pops items off it two at a time to get the current point and a pair of angles.
When path() encounters a `z` ([closepath](https://www.w3.org/Graphics/SVG/1.1/paths.html#PathDataClosePathCommand)) command, `None` is appended to the list in place of a pair of angles to mark the end of a sub-path, with the following `M` or `m` (moveto) adding the starting point of a new sub-path. If an `M` or `m` is used without a preceding `z`, however, only the …
=> Fix marker positions for unclosed paths

cairosvg/__init__.py
When running CPython in -OO mode, __debug__ is set to `False` and docstrings are stripped. This tries to handle this gracefully
=> Only update docstrings when not optimized

cairosvg/helpers.py
W3 mandates this behavior as the fallback assumption.
https://www.w3.org/TR/css-values-3/#font-relative-lengths
> In the cases where it is impossible or impractical to determine the
> measure of the "0" glyph, it must be assumed to be 0.5em wide by 1em
> tall. Thus, the ch unit falls back to 0.5em in the general case, and
> to 1em when it would be typeset upright (i.e. writing-mode is
> vertical-rl or vertical-lr and text-orientation is upright).
I'm happy to add a test for this, but would you mind offering a suggestion as to where it should go?  I had edited one into `test_non_regression/svg/coords-units-03-b.svg` as the place where it looked like other units were being tested, but then I realized that's an official SVG 1.1 test.  I don't see a 3rd edition test suite, and the SVG 1.2 …
=> Assume that 'ch' is 0.5em wide.

.github/workflows/tests.yml, cairosvg/features.py
locale.getdefaultlocale has started to give a DeprecationWarning in Python 3.11.
As far as I can cell, locale.getlocale should be used instead
This warning is (for example) causing these tests to fail: https://github.com/mscroggs/symfem/actions/runs/3657916856/jobs/6182054650
=> getdefaultlocale -> getlocale

cairosvg/__init__.py, cairosvg/__main__.py, cairosvg/test_api.py, cairosvg/url.py
Use `pathlib.Path` for path operations where possible. The test methods are then calling the code with strings, so it would be nice to make the code working for `os.PathLike` in general.
=> Use pathlib

cairosvg/parser.py
Fixes a TypeError when checking if input is gzipped using `bytestring.startswith(b"\x1f\x8b")`.
```bash
File ".../site-packages/cairosvg/parser.py", line 447, in __init__
if bytestring.startswith(b"\x1f\x8b"):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```
This patch ensures `bytestring` is properly encoded as `bytes` before gzip header detection.
=> Ensure bytestring is bytes before checking for gzip header
